name: bulid 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-minify-plugin~=0.8.0
      # - run: mkdocs gh-deploy --force
      ################################################################
      #############创建可以部署的静态文件################################
      - run: mkdocs build 
      - run: ls /home/runner/work/m17y.github.io/m17y.github.io/site | grep -v site | xargs rm -rf
      - run: git push origin --delete site-Page
      - run: git branch -M site-Page
      - run: git add -A 
      - run: ls -l
      - run: git commit -am 'update site-Page'
      - run: git push -u origin2 site-Page --force