name: bulid 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-minify-plugin~=0.8.0
      # - run: mkdocs gh-deploy --force
      - run: mkdir /home/runner/work/site
      - run: mkdocs build -d /home/runner/work/site
      - run: cd /home/runner/work/site
      - run: git remote add origin2 https://github.com/m17y/m17y.github.io.git
      - run: git branch -M sitePage
      - run: git push -u origin2 sitePage --force